all:
#	python mixedALearn.py 0.99 0.99
#	python mixedELearn.py 0.99 0.99
#	python mixedFlex.py 0.99 0.99
#	python mixedTest.py 0.99 0.99
#	python mixedARel.py 0.99 0.99
#	python mixedALearn.py 0.99 0.9
#	python mixedFlex.py 0.99 0.9
#	python mixedTest.py 0.99 0.9
#	python mixedALearn.py 0.9 0.99
#	python mixedELearn.py 0.9 0.99
#	python mixedFlex.py 0.9 0.99
#	python mixedTest.py 0.9 0.99
#	python mixedALearn.py 0.9 0.9
	python mixedFlex.py 0.9 0.9
	python mixedTest.py 0.9 0.9
	python mixedARel.py 0.9 0.9
	python mixedELearn.py 0.99 0.9
	python mixedELearn.py 0.9 0.9
