loops = 15
subloops = 20

all:
	python agentRelOverTime.py 0.99 $(loops) $(subloops)
	python agentRelOverTime.py 0.9 $(loops) $(subloops)
	python envRelOverTime.py 0.99 $(loops) $(subloops)
	python envRelOverTime.py 0.9 $(loops) $(subloops)
