rel1 = 1
rel2 = 0.99
rel3 = 0.9
all:
	python transitivityAgentRelTest.py $(rel1)
	python transitivityAgentRelTimeTest.py $(rel1)
	python transitivityEnvRelTest.py $(rel1)
	python transitivityEnvRelTimeTest.py $(rel1)
	python transitivityAgentRelTest.py $(rel2)
	python transitivityAgentRelTimeTest.py $(rel2)
	python transitivityEnvRelTest.py $(rel2)
	python transitivityEnvRelTimeTest.py $(rel2)
	python transitivityAgentRelTest.py $(rel3)
	python transitivityAgentRelTimeTest.py $(rel3)
	python transitivityEnvRelTest.py $(rel3)
	python transitivityEnvRelTimeTest.py $(rel3)
