all:
#	python mixedALearnELearn.py 0.99 0.99
#	python mixedFlexELea.py 0.99 0.99
#	python mixedALearnELearn.py 0.9 0.99
#	python mixedFlexELea.py 0.9 0.99
	python mixedArelTest.py 0.99 0.99
	pyton mixedFlexARel.py 0.99 0.99
	python mixedArelTest.py 0.9 0.9
	pyton mixedFlexARel.py 0.9 0.9
	python mixedALearnELearn.py 0.99 0.9
	python mixedFlexELea.py 0.99 0.9
	python mixedALearnELearn.py 0.9 0.9
	python mixedFlexELea.py 0.9 0.9
