rel1 = 1
rel2 = 0.99
rel3 = 0.9
all:
	python guessAgentRelTest.py $(rel1)
	python guessAgentRelTimeTest.py $(rel1)
	python guessEnvRelTest.py $(rel1)
	python guessEnvRelTimeTest.py $(rel1)
	python guessAgentRelTest.py $(rel2)
	python guessAgentRelTimeTest.py $(rel2)
	python guessEnvRelTest.py $(rel2)
	python guessEnvRelTimeTest.py $(rel2)
	python guessAgentRelTest.py $(rel3)
	python guessAgentRelTimeTest.py $(rel3)
	python guessEnvRelTest.py $(rel3)
	python guessEnvRelTimeTest.py $(rel3)
