all:
#	python agentRelOverTime.py 1
#	python agentRelOverTime.py 0.99
#	python agentRelOverTime.py 0.9
#	python envRelOverTime.py 1
#	python envRelOverTime.py 0.99
#	python envRelOverTime.py 0.9
	python flexAlpha.py -0.5
	python flexAlpha.py -0.75
	python flexAlpha.py -1
	python flexAlpha.py 0
	python flexAlpha.py 0.5
	python flexAlpha.py 0.75
	python flexAlpha.py 1
